### ISSUE TITLE
Throttling Compression Operation?

### ISSUE THREAD

**Issue by taylorchasewhite** [mjebrahimi/EasyCompressor#184]
Hi, I'm using the LZMA Compressor, and one thing I notice is that when the compression is happening, it basically takes all of my server's resources. Is there a way to throttle this back so it takes longer but uses fewer resources?

**Comment by mjebrahimi** [comment]
Hi, I recommend using other algorithms such as LZ4 or Brotli if it's possible for you because LZMA itself or maybe the current implementation (LZMA-SDK package) that EasyCompressor uses is not so efficient (both in CPU usage and Memory usage).  

Just so you know, if you decide to use Brotli make sure to use the .NET built-in Brotli implementation which is included in EasyCompressor package (not the EasyCompressor.BrotliNET).

Also, make sure to use `CompressionLevel.Optimal` (that is by default in EasyCompressor) because the `CompressionLevel.SmallestSize` takes too long to process and is not cost-effective.

By the way, there is no way to throttle only a method in .NET to limit CPU or Memory usage.

But If you use orchestrators like Kubernetes or Cloud-based infrastructures you can limit your CPU Cores.

You can also limit your **Entire Process** through Windows by setting **Process Priority** to **Low** and **Process Affinity** to **Minimum CPU Cores** ([like this](https://windowsreport.com/limit-cpu-usage/#how-to-limit-the-cpu-usage-of-a-program) or by [third-party apps](https://superuser.com/questions/214566/are-there-solutions-that-can-limit-the-cpu-usage-of-a-process))

However, I think can't limit your Memory usage because if you don't have enough memory you will run into `OutOfMemoryException`

You can do the same using C# by setting **Priority** and **Affinity** of your Current `Process `or `ProcessThread `like this:
```cssharp
Process currentProcess = Process.GetCurrentProcess();

currentProcess.PriorityClass = ProcessPriorityClass.Idle; //Low

int affinityHex = 0x0002; // use only the second processor, despite availability
//affinityHex = 0x000F; // use only any of the first 4 available processors

currentProcess.ProcessorAffinity = affinityHex;

//ProcessThread processThread = currentProcess.Threads[0];
//processThread.PriorityLevel = ThreadPriorityLevel.Idle;
//processThread.ProcessorAffinity = affinityHex;
```

**Note:** The value of affinity is hex-base and you must calculate it based on which CPU Core/s you want to be available for this process. ([more info](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processoraffinity) and [here](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processthread.processoraffinity))
