### ISSUE TITLE
Possibly add ZPAQ or other compressors?

### ISSUE THREAD

**Issue by unquietwiki** [mjebrahimi/EasyCompressor#50]
Hey there. http://mattmahoney.net/dc/ has a bunch of compression stuff; ZPAQ being the most "complete". It's meant for standardized heavy-duty compression; there are some other algorithms too that might be of interest. Thanks!

**Comment by unquietwiki** [comment]
@mjebrahimi thanks for replying. I posted about the project on Reddit just now; I wasn't sure if you had access to it in Iran, or not.  As for the stuff from Matt Mahoney, I figured it'd be possible to employ one or two of the streaming compressors on there; your targeted use of this for distributed storage is similar to ideas I've had myself.

https://www.reddit.com/r/csharp/comments/j3puv0/easycompressor_is_an_opensource_compression/

**Comment by mjebrahimi** [comment]
Thank you @unquietwiki for sharing. I access to anything with proxy ;)
Since we now support the most popular algorithms, If I have the opportunity, I decide to write extensions to integrate EasyConpressor with other libraries and tools like:
- `Microsoft.Extensions.Caching.Distributed.IDistributedCache`
- [CacheManager](https://github.com/MichaCo/CacheManager)
- And wherever compression can be useful.

**Comment by unquietwiki** [comment]
@mjebrahimi This all looks cool! I bookmarked both this & the CacheManager thing to look at for future project ideas. I hope your project picks up further in interest, and your .NET group stuff continues to do well!
