### ISSUE TITLE
Brotli,Deflate,GZIP closes stream too early.

### ISSUE THREAD

**Issue by jetersen** [mjebrahimi/EasyCompressor#78]
This example works with LZMACompressor

I should submit a repro :)

```csharp
        public async Task<MemoryStream> CreateArchiveAsMemoryStreamAsync(ICompressor compressor, IEnumerable<string> files,
            CancellationToken cancellationToken = default)
        {
            MemoryStream outStream = new();

            await using (MemoryStream zipStream = new())
            {
                using (var zipArchive = new ZipArchive(zipStream, ZipArchiveMode.Create, leaveOpen: true))
                {
                    foreach (string filename in files)
                    {
                        await using Stream inputStream = File.OpenRead(filename);
                        string tarName = Path.GetFileName(filename);

                        var entry = zipArchive.CreateEntry(tarName, CompressionLevel.NoCompression);
                        await using var entryStream = entry.Open();
                        await inputStream.CopyToAsync(entryStream, cancellationToken);
                    }
                }

                zipStream.Position = 0;
                await using (var fileStream = File.OpenWrite("test.zip"))
                {
                    await zipStream.CopyToAsync(fileStream, cancellationToken);
                }

                zipStream.Position = 0;
                await compressor.CompressAsync(zipStream, outStream, cancellationToken);

                outStream.Position = 0;
                await using (var fileStream = File.OpenWrite("test.zip.compressed"))
                {
                    await outStream.CopyToAsync(fileStream, cancellationToken);
                }
            }

            outStream.Position = 0;
            return outStream;
        }
```

**Comment by mjebrahimi** [comment]
Interesting point.   
Let me examine the problem.

**Comment by jetersen** [comment]
Most stream API have an option for leave open, which would be a good approach imho.

**Comment by mjebrahimi** [comment]
We have 4 approaches to solve this problem.

1- Adding `leaveOutputStreamOpen ` parameter to `Compress` methods since `Compress` methods currentlty dispose only the output stream. (which passed to Encoder/Compressor stream like [LZ4Stream.Encode(**outputStream**)](https://github.com/mjebrahimi/EasyCompressor/blob/87981a753b331f1480edffbd7943bd4034a39a6f/src/EasyCompressor.LZ4/LZ4Compressor.cs#L57) )
And adding `leaveInputStreamOpen` parameters to `Decompress` methods since `Decompress` methods currently dispose only the input stream. (which passed to Decoder/Decompressor stream like [LZ4Stream.Decode(**inputStream**)](https://github.com/mjebrahimi/EasyCompressor/blob/87981a753b331f1480edffbd7943bd4034a39a6f/src/EasyCompressor.LZ4/LZ4Compressor.cs#L69) )

2- Adding an option (like `LeaveOpenSettings`) that has two property (`leaveOutputStreamOpen` and `leaveInputStreamOpen`) to `Compress` and `Decompress` methods to determine which input/output streams must be disposed after operation completes.

3- And Adding just one `leaveOpen` parameter to both `Compress` and `Decompress` methods to leave open both input and output streams if it is `true` and dispose them manually if it is `false`.
**Note:** In this way, we have **breaking changes** because these methods dispose both streams (something that has not been done before) if it is `false` (By default, the `leaveOpen` parameter will be `false`)

**Note:** All three approaches above will require method signature changes and for `CompressAsync` and `DecompressAsync` that has `CancellationToken` as the third parameter currently (instead of `leaveOpen`) cause **breaking changes** but we can fix this problem by adding two extension methods to `ICompressor` that gives `CancellationToken` as the third parameter and pass the default value (false) to `leaveOpen` at the method call to main Compress/Decompress methods.

4- No adding any parameter to `Compress` and `Decompress` methods. Just pass `leaveOpen: true` to underlying Encoder/Decoder streams to prevent from disposing input and output streams. (like `LZ4Stream.Encode(outputStream, leaveOpen: true)`)
**Note:** In with way, unlike previous approaches we have not any method signature changes.
But we have a minimum breaking changes because Compress/Decompress methods no longer dispose any streams (something that has not been done before). 

IMO, approach 4 is better choice because require no method signature changes and also disposing the streams is not related to Compress/Decompress methods and it is not their jobs.

Now, what do you think? I would like to know your opinion.

**Comment by mjebrahimi** [comment]
Currently, [this test](https://github.com/mjebrahimi/EasyCompressor/blob/1a3f739a89146219699ffa482977882840ab375a/test/EasyCompressor.Tests/StreamTests.cs#L127) (that checks streams are not closed after Compress/Decompress completes) is passed regard to approach 4 (passing `leaveOpen: true` to underlying Encoder/Decoder streams without adding any parameters to Compress/Decompress methods)

**Comment by jetersen** [comment]
I think approach four is suitable as it would usually be surrounded by a stream with an using statement.

**Comment by mjebrahimi** [comment]
I also agree.
[Version 1.4.0](https://www.nuget.org/packages/EasyCompressor/1.4.0) was released in order to fix this issue.

**Comment by jetersen** [comment]
@mjebrahimi thanks for fixing the issue :)

**Comment by mjebrahimi** [comment]
@jetersen thank you for the report and contribution.
